function theScript() {
	return {


		main: [
			[ACTION_SETVAR, "qIntel", null],
			[ACTION_GOTO, "a1"],
		],


		a1: [ // Act 1: main
			[ACTION_SYSTEM, "— Connecting —"],
			[ACTION_PAUSE, 900],
			[ACTION_SYSTEM, "— Connection established —"],
			[ACTION_TYPING, 1600, 900],
			[ACTION_TEXT, ["Hi"]],
			[ACTION_TYPING, 400, 1700],
			[ACTION_TEXT, ["I know this must be confusing for you..."]],
			[ACTION_TYPING, 400, 1300],
			[ACTION_TEXT, ["Just, don't panic. Okay?"]],
			[ACTION_PAUSE, 500],
			[ACTION_PROMPT, [["Who are you?", "a1u"], ["Where am I?", "a1is"]]],
		],

		a1u: [ // Act 1: who are you
			[ACTION_SPEAK, ["Who are you?"]],
			[ACTION_TYPING, 400, 1700],
			[ACTION_TEXT, ["I'm your P.A.L."]],
			[ACTION_PAUSE, 800],
			[ACTION_SPEAK, ["P.A.L?"]],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["Primary Access Link"]],
			[ACTION_TYPING, 400, 1700],
			[ACTION_TEXT, ["Yeah, I know.", "It sucks."]],
			[ACTION_TYPING, 400, 1400],
			[ACTION_TEXT, ["Just call me Pal."]],
			[ACTION_PAUSE, 500],
			[ACTION_PROMPT, [["Hi Pal.", "a1u2"], ["Where am I Pal?", "a1i"]]],
		],

		a1u2: [ // Act 1: who are you followup
			[ACTION_SPEAK, ["Hi Pal."]],
			[ACTION_TYPING, 400, 1700],
			[ACTION_TEXT, ["Well hi to you to! Good to", "see you're taking this so well", "given where you are."]],
			[ACTION_GOTO, "a1i"],
		],

		a1is: [ // Act 1: Where am I direct
			[ACTION_SPEAK, ["Where am I?"]],
			[ACTION_TYPING, 400, 1700],
			[ACTION_TEXT, ["What, no hello?", "No, hi, nice to meet you?"]],
			[ACTION_TYPING, 400, 1500],
			[ACTION_TEXT, ["I'm P.A.L. by the way."]],
			[ACTION_TYPING, 400, 1900],
			[ACTION_TEXT, ["It stands for Primary Access", "Link, but I guess you don't", "care about that either."]],
			[ACTION_PAUSE, 500],
			[ACTION_GOTO, "a1i"],
		],

		a1i: [ // Act 1: Where am I?
			[ACTION_SPEAK, ["Where am I Pal?"]],
			[ACTION_TYPING, 400, 1700],
			[ACTION_TEXT, ["You're safe."]],
			[ACTION_PAUSE, 500],
			[ACTION_PROMPT, [["That's reassuring.", "a1ir"], ["That's not what I asked!", "a1ia"]]],
		],

		a1ir: [ // Act 1: Where am I? => Reassured
			[ACTION_SPEAK, ["Well that's reassuring."]],
			[ACTION_TYPING, 400, 1100],
			[ACTION_TEXT, ["Phew!"]],
			[ACTION_TYPING, 400, 1700],
			[ACTION_TEXT, ["The last guy flipped.", "You seem much calmer!"]],
			[ACTION_GOTO, "a2"],
		],
		a1ia: [ // Act 1: Where am I? => Angry
			[ACTION_SPEAK, ["That's not what I asked!"]],
			[ACTION_TYPING, 400, 1100],
			[ACTION_TEXT, ["Hey hey!"]],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["Calm down, okay?", "I'm trying to explain this", "slowly for you."]],
			[ACTION_GOTO, "a2"],
		],


		a2: [ // Act 2
			[ACTION_TYPING, 400, 1600],
			[ACTION_TEXT, ["This is going to be a shock but..."]],
			[ACTION_SYSTEM, "— Connection lost, retrying... —"],
			[ACTION_PAUSE, 900],
			[ACTION_SYSTEM, "— Connected —"],
			[ACTION_TYPING, 1600, 900],
			[ACTION_TEXT, ["Huh"]],
			[ACTION_TYPING, 1600, 1800],
			[ACTION_TEXT, ["That shouldn't happen"]],
			[ACTION_TYPING, 1600, 1500],
			[ACTION_TEXT, ["How are you feeling?"]],
			[ACTION_PAUSE, 500],
			[ACTION_PROMPT, [["I'm confused", "a2c"], ["I'm angry", "a2a"], ["I'm lost", "a2l"]]],
		],
		a2c: [ // Act 2: Confused
			[ACTION_SPEAK, ["I'm a bit confused. What's", "going on?"]],
			[ACTION_TYPING, 400, 1100],
			[ACTION_TEXT, ["Let's start at the beginning."]],
			[ACTION_GOTO, "a2e"],
		],
		a2a: [ // Act 2: Angry
			[ACTION_SPEAK, ["Just tell me what's going on already!"]],
			[ACTION_TYPING, 400, 1100],
			[ACTION_TEXT, ["It's not that simple."]],
			[ACTION_TYPING, 400, 1100],
			[ACTION_TEXT, ["How about we start at the beginning."]],
			[ACTION_GOTO, "a2e"],
		],
		a2l: [ // Act 2: Lost
			[ACTION_SPEAK, ["I'm lost. Where am I Pal?", "Why am I here?"]],
			[ACTION_TYPING, 400, 1100],
			[ACTION_TEXT, ["I know it's scary, but bear with", "me. Let's start at the beginning yeah?"]],
			[ACTION_GOTO, "a2e"],
		],

		a2e: [ // Act 2: Explanation
			[ACTION_TYPING, 400, 1100],
			[ACTION_TEXT, ["What's the last thing you remember?"]],
			[ACTION_PAUSE, 500],
			[ACTION_PROMPT, [["The light", "a2el"], ["The sound", "a2es"], ["The pain", "a2ep"]]],
		],
		a2el: [ // Act 2: Explain light
			[ACTION_SPEAK, ["I remember a blinding light.", "It was so close, I couldn't", "see anything else."]],
			[ACTION_GOTO, "a2e2"],
		],
		a2es: [ // Act 2: Explain sound
			[ACTION_SPEAK, ["I remember a sound.", "Like a bomb going off", "right next to my ear."]],
			[ACTION_GOTO, "a2e2"],
		],
		a2ep: [ // Act 2: Explain pain
			[ACTION_SPEAK, ["I remember the pain.", "Felt like I was hit by a", "dump truck right in the chest!"]],
			[ACTION_GOTO, "a2e2"],
		],
		a2e2: [ // Act 2: Explain confirm
			[ACTION_TYPING, 400, 1900],
			[ACTION_TEXT, ["That's good.", "Well not good, but at least", "you remember something."]],
			[ACTION_TYPING, 400, 1500],
			[ACTION_TEXT, ["It will make this easier."]],
			[ACTION_PAUSE, 500],
			[ACTION_SPEAK, ["???"]],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["You're dead"]],
			[ACTION_SYSTEM, "— Connection lost, retrying... —"],
			[ACTION_PAUSE, 900],
			[ACTION_SYSTEM, "— Retry failed, retrying #2... —"],
			[ACTION_PAUSE, 700],
			[ACTION_SYSTEM, "— Connected —"],
			[ACTION_TYPING, 1600, 900],
			[ACTION_TEXT, ["Great timing techs. Really great."]],
			[ACTION_PAUSE, 500],
			[ACTION_SPEAK, ["I'm dead?!"]],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["Yes, but don't panic, remember?"]],
			[ACTION_PAUSE, 500],
			[ACTION_PROMPT, [["I'm dead!", "a2e2d"], ["I'm scared!", "a2e2s"]]],
		],
		a2e2d: [ // Act 2: Dead
			[ACTION_SPEAK, ["I'm dead! How am I not", "supposed to panic?!"]],
			[ACTION_TYPING, 400, 1700],
			[ACTION_TEXT, ["Because we haven't lost you yet."]],
			[ACTION_GOTO, "a3"],
		],
		a2e2s: [ // Act 2: Scared
			[ACTION_SPEAK, ["I'm scared Pal. I don't", "feel like I'm dead."]],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["That's good.", "Stick with that."]],
			[ACTION_TYPING, 400, 1700],
			[ACTION_TEXT, ["Because we haven't lost you yet."]],
			[ACTION_GOTO, "a3"],
		],


		a3: [ // Act 3
			[ACTION_TYPING, 400, 1100],
			[ACTION_TEXT, ["You were hurt.", "Your heart has stopped."]],
			[ACTION_TYPING, 400, 1900],
			[ACTION_TEXT, ["We're trying to save you, but", "we need to talk to you first."]],
			[ACTION_PAUSE, 500],
			[ACTION_SPEAK, ["Talk to me?"]],
			[ACTION_PAUSE, 500],
			[ACTION_PROMPT, [["Why so urgent?", "a3u"], ["Save me first!", "a3s"]]],
		],
		a3u: [ // Act 3: urgent
			[ACTION_SPEAK, ["What could be more urgent", "than saving my life?"]],
			[ACTION_TYPING, 400, 1600],
			[ACTION_TEXT, ["You have some intel..."]],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["And we need to make sure it gets", "to the right people as soon", "as possible."]],
			[ACTION_PAUSE, 500],
			[ACTION_PROMPT, [["What kind of intel?", "a3ik"], ["And it's worth risking my life for?", "a3ir"]]],
		],
		a3s: [ // Act 3: save me
			[ACTION_SPEAK, ["How about you save me first yeah?"]],
			[ACTION_TYPING, 400, 1200],
			[ACTION_TEXT, ["We're trying!"]],
			[ACTION_TYPING, 400, 1000],
			[ACTION_TEXT, ["We're doing everything we can."]],
			[ACTION_TYPING, 400, 1600],
			[ACTION_TEXT, ["But you have some intel..."]],
			[ACTION_TYPING, 400, 2000],
			[ACTION_TEXT, ["And we need to make sure it gets", "to the right people as soon", "as possible."]],
			[ACTION_PAUSE, 500],
			[ACTION_PROMPT, [["What kind of intel?", "a3ik"], ["And it's worth risking my life for?", "a3ir"]]],
		],
		a3ik: [ // Act 3: intel kind
			[ACTION_SETVAR, "qIntel", true],
			[ACTION_SPEAK, ["What kind of intel?"]],
			[ACTION_TYPING, 400, 1200],
			[ACTION_TEXT, ["Good, you're asking the right questions."]],
			[ACTION_GOTO, "a3i2"],
		],
		a3ir: [ // Act 3: intel risk
			[ACTION_SPEAK, ["And it's worth risking my life for?"]],
			[ACTION_TYPING, 400, 1200],
			[ACTION_TEXT, ["From what I've been told, yeah."]],
			[ACTION_PAUSE, 700],
			[ACTION_SPEAK, ["'From what you've been told?'", "You don't even know what it is?"]],
			[ACTION_GOTO, "a3i2"],
		],

		a3i2: [ // Act 3: intel
			[ACTION_TYPING, 400, 1700],
			[ACTION_TEXT, ["It's intel vital to the war effort."]],
			[ACTION_TYPING, 400, 1200],
			[ACTION_TEXT, ["We can't let it get into the wrong hands."]],
			[ACTION_PAUSE, 500],
			[ACTION_PROMPT, [["The war?", "a3i2w"], ["The wrong hands?", "a3i2e"]]],
		],
		a3i2w: [ // Act 3: intel war
			[ACTION_SPEAK, ["Wait, there's a war going on?"]],
			[ACTION_TYPING, 400, 1000],
			[ACTION_TEXT, ["Oh boy"]],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["Yes. We are at war. Now, don't", "freak out at this next part okay?"]],
			[ACTION_GOTO, "a4"],
		],
		a3i2e: [ // Act 3: intel enemy
			[ACTION_SPEAK, ["Who the hell are we fighting against?"]],
			[ACTION_TYPING, 400, 1400],
			[ACTION_TEXT, ["This is going to be a shock."]],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["And I don't want you to freak out, okay?"]],
			[ACTION_GOTO, "a4"],
		],


		a4: [ // Act 4: Enter Aliens
			[ACTION_PAUSE, 500],
			[ACTION_SPEAK, ["Freak out?!"]],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["They're aliens."]],
			[ACTION_GOTO, "a4"],
			[ACTION_SYSTEM, "— Connection lost, retrying... —"],
			[ACTION_PAUSE, 1100],
			[ACTION_SYSTEM, "— Retry failed, retrying #2... —"],
			[ACTION_PAUSE, 1900],
			[ACTION_SYSTEM, "— Connected —"],
			[ACTION_SYSTEM, "— Warning: Link Unstable —"],
			[ACTION_TYPING, 1600, 900],
			[ACTION_TEXT, ["You need to calm down."]],
			[ACTION_PAUSE, 500],
			[ACTION_PROMPT, [["Aliens!", "a4a"], ["ALIENS!", "a4aa"]]],
		],
		a4aa: [ // Act 4: ALIENS!
			[ACTION_SPEAK, ["Calm down?!"]],
			[ACTION_PAUSE, 900],
			[ACTION_SPEAK, ["CALM DOWN?!"]],
			[ACTION_PAUSE, 1700],
			[ACTION_GOTO, "a4a"],
		],
		a4a: [ // Act 4: Aliens!
			[ACTION_SPEAK, ["You just told me we're at war with aliens!"]],
			[ACTION_PAUSE, 1800],
			[ACTION_SPEAK, ["How can I be calm right now?"]],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["Because otherwise you'll hurt yourself."]],
			[ACTION_PAUSE, 1100],
			[ACTION_SPEAK, ["You mean more than being dead?"]],
			[ACTION_TYPING, 400, 1000],
			[ACTION_TEXT, ["Yes."]],
			[ACTION_PAUSE, 500],
			[ACTION_SPEAK, ["Oh."]],
			[ACTION_PAUSE, 400],
			[ACTION_PROMPT, [["What do they want?", "a4aw"], ["Why am I so important?", "a4ai"]]],
		],
		a4aw: [ // Act 4: Alien wants
			[ACTION_SPEAK, ["So...", "What do these aliens want?"]],
			[ACTION_TYPING, 400, 1200],
			[ACTION_TEXT, ["Oh the usual."]],
			[ACTION_TYPING, 400, 2100],
			[ACTION_TEXT, ["Take over the world.", "Steal our resources.", "Enslave the population."]],
			[ACTION_PAUSE, 500],
			[ACTION_SPEAK, ["And me?"]],
			[ACTION_TYPING, 400, 2100],
			[ACTION_TEXT, ["You have some very valuable intel in your head."]],
			[ACTION_TYPING, 400, 1500],
			[ACTION_TEXT, ["And we need to get it out."]],
			[ACTION_GOTO, "a4b"],
		],
		a4ai: [ // Act 4: Player importance?
			[ACTION_SPEAK, ["So...", "Why am I so important?"]],
			[ACTION_TYPING, 400, 1200],
			[ACTION_TEXT, ["I already told you"]],
			[ACTION_TYPING, 400, 2100],
			[ACTION_TEXT, ["These aliens want to take over the", "planet, steal our resources,", "enslave the population."]],
			[ACTION_TYPING, 400, 1900],
			[ACTION_TEXT, ["And you have the intel in your", "head to stop them."]],
			[ACTION_TYPING, 400, 1500],
			[ACTION_TEXT, ["So we need to get it out."]],
			[ACTION_GOTO, "a4b"],
		],


		a5: [ // Act 5: Me or the Mission
			[ACTION_PAUSE, 600],
			[ACTION_SPEAK, ["Before I die you mean."]],
			[ACTION_TYPING, 400, 1500],
			[ACTION_TEXT, ["We're not giving up on you yet."]],
			[ACTION_PAUSE, 400],
			[ACTION_PROMPT, [["Save the intel", "a5i"], ["Save me first", "a5m"]]],
		],
		a5i: [ // Act 5: Save intel
			[ACTION_SPEAK, ["Save the intel"]],
			[ACTION_PAUSE, 800],
			[ACTION_SPEAK, ["If it can save the human race,", "it's more important than me."]],
			[ACTION_TYPING, 400, 1200],
			[ACTION_TEXT, ["Good man."]],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["That's what we like to see,", "putting others before yourself."]],
			[ACTION_PAUSE, 400],
			[ACTION_PROMPT, [["What's the risk?", "a5r"], ["What's the intel?", "a5ii"]]],
		],
		a5m: [ // Act 5: Save me
			[ACTION_SPEAK, ["Save me first!"]],
			[ACTION_PAUSE, 800],
			[ACTION_SPEAK, ["If I die you're getting nothing."]],
			[ACTION_TYPING, 400, 1200],
			[ACTION_TEXT, ["We're doing everything we can."]],
			[ACTION_TYPING, 400, 1900],
			[ACTION_TEXT, ["But if something goes wrong..."]],
			[ACTION_PAUSE, 400],
			[ACTION_PROMPT, [["What's the risk?", "a5r"], ["What's the intel?", "a5ii"]]],
		],
		a5r: [ // Act 5: Whats the risk
			[ACTION_SPEAK, ["What's the risk?"]],
			[ACTION_TYPING, 400, 1200],
			[ACTION_TEXT, ["Not gonna lie."]],
			[ACTION_TYPING, 400, 1900],
			[ACTION_TEXT, ["You might not make it through but", "we're trying everything we can."]],
		],
		a5ii: [ // Act 5: What's the intel
			[ACTION_SPEAK, ["What's the intel?"]],
			[ACTION_TYPING, 400, 1500],
			[ACTION_IFVAR, "qIntel", {
				true: [ACTION_TEXT, ["You asked about the intel before."]],
				null: [ACTION_TEXT, ["So now you're interested in the intel."]],
			}],
			[ACTION_TYPING, 400, 1800],
			[ACTION_TEXT, ["You have the launch codes."]],
			[ACTION_PAUSE, 600],
			[ACTION_SPEAK, ["For?"]],
			[ACTION_TYPING, 400, 1300],
			[ACTION_TEXT, ["Everything."]],
		],





		debug: [ // Debug text
			[ACTION_SYSTEM, "System text"],
			[ACTION_TEXT, ["Single line of them text"]],
			[ACTION_TEXT, ["Multi-line 1", "Multi-line 2 longer", "Multi-line 3"]],
			[ACTION_SPEAK, ["Player speaking"]],
		],


	};
}
